# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "nvme" ];
  boot.kernel.sysctl = { "vm.swappiness" = 0; };
  boot.supportedFilesystems = [ "ntfs" "exfat" ];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_zen;
  boot.kernelParams = [
    "boot.shell_on_fail"
    "pci=noats"
    "pcie_acs_override=downstream,multifunction"
    "usbcore.old_scheme_first=y"

    # Maybe fix NVME QID timeouts
    # https://wiki.archlinux.org/title/Solid_state_drive/NVMe#Controller_failure_due_to_broken_APST_support
    "nvme_core.default_ps_max_latency_us=5000"
  ];
  boot.kernelModules = [
    # "kvm-amd"
    # "amdgpu"
    # "vfio_virqfd"
    # "vfio_pci"
    # "vfio_iommu_type1"
    # "vfio"
    "uvcvideo"
  ];

  boot.extraModprobeConfig = ''
    options uvcvideo quirks=4
  '';

  boot.extraModulePackages = with config.boot.kernelPackages; [
    xpadneo
    zenpower
    v4l2loopback
  ];

  # nixpkgs.config.packageOverrides = pkgs: {
  #   linuxPackages_zen = pkgs.linuxPackages_zen.override {
  #     kernelPatches = pkgs.linuxPackages_zen.kernelPatches ++ [
  #       { name = "acs";
  #         patch = pkgs.fetchurl {
  #           url = "https://aur.archlinux.org/cgit/aur.git/plain/add-acs-overrides.patch?h=linux-vfio";
  #           sha256 = "5517df72ddb44f873670c75d89544461473274b2636e2299de93eb829510ea50";
  #         };
  #       }
  #     ];
  #   };
  # };

  services.xserver.videoDrivers = [ "modesetting" ];

  fileSystems."/" = {
    # 71a653f5-bb05-46b1-bbe4-950652b44cf7
    device = "/dev/disk/by-uuid/71a653f5-bb05-46b1-bbe4-950652b44cf7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    # D209-1E91
    device = "/dev/disk/by-uuid/D209-1E91";
    fsType = "vfat";
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/673fc3ca-f732-48b4-9b49-13c5d104f3cd";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/mnt/ram" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "nofail" "size=20G" "mode=777" "user" ];
  };

  fileSystems."/mnt/disk0" = {
    device = "/dev/disk/by-id/usb-HL-DT-ST_DVD+-RW_GT10N_DD56419883915-0:0";
    fsType = "auto";
    options = [ "ro" "user" "noauto" "unhide" "nofail" ];
  };

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.opengl.package = pkgs.mesa.drivers;
  hardware.opengl.package32 = pkgs.pkgsi686Linux.mesa.drivers;
  hardware.opengl.extraPackages = [ pkgs.mesa.opencl ];
}
